/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;
import javax.swing.*;
public class App {
    public static void main(String[]args){
   SwingUtilities.invokeLater(()->{
   String studentNumber = JOptionPane.showInputDialog("Enter student Number: ");
   String  name = JOptionPane.showInputDialog("Name: ");
   String surname = JOptionPane.showInputDialog("Suname: ");
   String email = JOptionPane.showInputDialog("Email: ");
   String phoneNumber = JOptionPane.showInputDialog("Phone Number: ");
  
        int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 1: "));
          int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 2: "));
         int assignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark assignment Mark: "));
      int examMark = Integer.parseInt(JOptionPane.showInputDialog("examMark:"));
  
  boolean dpStatus = ((mark1+mark2+assignmentMark)/3) >=40;
  
  double courseworkAverage = (mark1+mark2+assignmentMark)/3 ;
  double finalMark = (courseworkAverage*0.4)+(examMark*0.6);
  
  String message = "Student Number: " +"/n"  +studentNumber +"/n"
          +"Name: " + name + surname +"\n"
          +"Email: " + email +"\n"
          +"Phone Number: " + phoneNumber +"\n"
          +"Mark 1: " + mark1 +"\n"
          +"Mark 2: " + mark2 +"\n"
          +"Assignemnt Mark: " + assignmentMark +"\n"
          +"dp status: " + (dpStatus? "achieved" : "Not achieved") +"\n"
          +"final status: " + finalMark;
     
  JOptionPane.showMessageDialog(null,message);  
   System.out.println(message);
  
           }); 
  
}
}
